# Generated by Django 5.1.3 on 2024-11-18 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tango", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tango.place",
            ),
        ),
    ]
