# Generated by Django 5.1.3 on 2024-11-15 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tango", "0002_remove_activity_count_likes_alter_member_occupations"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="additional_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="team_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
